### ISSUE TITLE
Does this work with GRBL 1.1?

### ISSUE THREAD

**Issue by tingles2233** [bdring/Grbl_Pen_Servo#3]
Hello, 

Haven`t tried this yet, but I know a lot of previous pen servo modifications only worked on 0.9GRBL not the latest 1.1 Just thought I would ask before trying it on mine and breaking my current setup should it just straight up be not compatible. 

Thanks in advance!

**Comment by pcace** [comment]
have you had any success?

**Comment by saintofinternet** [comment]
am i missing something?? :-)

**Comment by akasoggybunz** [comment]
Has anyone had success with latest version of GRBL? I can't get the servo to react how I want with z commands only works with spindle commands M03 m05.
